### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Zero3K** [rw3r45/opssl-patches#1]
It would be nice if someone could get it to work for compiling under Windows OSs.

**Comment by rw3r45** [comment]
894b41600c4b93c132952079fa7bfb60bd30a2c8 should fix compilation on windows for 1.0.0q and 1.0.0t

The 1.0.1 probably doesn't compile outside x86 Linux and honestly is even a bigger mess than the 1.0.0 branch.

**Comment by PhonyWelder** [comment]
Thanks, 1.0.1u compiles in VS2010 after moving cmac.h from modules\libopeay\crypto\cmac\ to modules\libopeay\openssl\

**Comment by rw3r45** [comment]
Thanks for the info. I'll add cmac.h to openssl folder when I have some free time.

The openssl directory appears to be a separate directory for header files used by VS. At this point I wouldn't bother much with it unless we see some windows-specific crashes occuring, but we should make a mental note to update all header files in that directory if we ever get new cipher suites working.

**Comment by PhonyWelder** [comment]
Looked closer: modules\libopeay\openssl\*.h are just "aliases" for header files. Moved cmac.h back and created same: `#include "modules/libopeay/crypto/cmac/cmac.h"`

**Comment by rw3r45** [comment]
Added the include for cmac in 420164108951030793314ec89940910ed60f2b0e

**Comment by PhonyWelder** [comment]
1.0.2l: modules/libopeay/crypto/dh/dh_ameth.c
error C4065: switch statement contains 'default' but no 'case' labels

fix:
```
static int dh_pkey_ctrl(EVP_PKEY *pkey, int op, long arg1, void *arg2)
{
#ifndef OPENSSL_NO_CMS
    switch (op) {

    case ASN1_PKEY_CTRL_CMS_ENVELOPE:
        if (arg1 == 1)
            return dh_cms_decrypt(arg2);
        else if (arg1 == 0)
            return dh_cms_encrypt(arg2);
        return -2;

    case ASN1_PKEY_CTRL_CMS_RI_TYPE:
        *(int *)arg2 = CMS_RECIPINFO_AGREE;
        return 1;
    default:
        return -2;
    }
#else
    return -2;
#endif
}

```

**Comment by Zero3K** [comment]
Thanks for getting it to work under them. I am closing this issue since it has been resolved.
